version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "GAP"
leavesCullingAmount = 1
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
offroad = true
ohmymeteors = true
supplementaries = true
create_vibrant_vaults = true
createbigcannons = true
vista = true
createprism = true
tfmg = true
ldlib2 = true
createpropulsion = true
extra_gauges = true
rha = true
create = true
aeronautics = true
interiors = true
connectedglass = true
simulated = true
trashcans = true
minecraft = true
copycats = true
createoreexcavation = true
createadditionallogistics = true
architects_palette = true
ntgl = true
dndecor = true
create_connected = true
furniture = true
unusual_furniture = true
abyssal_decor = true
createdeco = true
createaddition = true
bits_n_bobs = true
compactflap = true
cbc_at = true
createlowheated = true
tracks = true
computercraft = true
ftbquests = true
protection_pixel = true
fluid = true
moonlight = true
sophisticatedbackpacks = true
born_in_chaos_v1 = true
create_radar = true
cgs = true
aeroworks = true
dndesires = true
