version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
offroad = true
ohmymeteors = true
supplementaries = true
createbigcannons = true
createprism = true
createpropulsion = true
tfmg = true
vista = true
rha = true
create = true
aeronautics = true
interiors = true
connectedglass = true
simulated = true
dndecor = true
architects_palette = true
trashcans = true
createoreexcavation = true
createadditionallogistics = true
copycats = true
ntgl = true
minecraft = true
unusual_furniture = true
furniture = true
abyssal_decor = true
create_connected = true
createdeco = true
createaddition = true
bits_n_bobs = true
compactflap = true
cbc_at = true
createlowheated = true
ftbquests = true
fluid = true
computercraft = true
moonlight = true
create_radar = true
born_in_chaos_v1 = true
cgs = true
sophisticatedbackpacks = true
dndesires = true
