[stage]
id = "medcraft_steel_processing"
display_name = "Steel Processing"
description = "Unlocks steel production and steel materials."
icon = "tfmg:steel_ingot"
unlock_message = "Steel Processing researched."
dependency = ""

[items]
locked = [
  "tfmg:steel_ingot",
  "createbigcannons:steel_ingot",
  "cgs:steel_ingot"
]
always_unlocked = []

[blocks]
locked = [
  "tfmg:steel_block",
  "tfmg:steel_casing"
]
always_unlocked = []

[recipes]
locked_ids = []
locked_items = [
  "tfmg:steel_ingot",
  "tfmg:steel_block",
  "tfmg:steel_casing",
  "createbigcannons:steel_ingot",
  "cgs:steel_ingot"
]
always_unlocked = []
