[stage]
id = "medcraft_nuclear_power"
display_name = "Nuclear Power"
description = "Unlocks nuclear reactor components and uranium processing."
icon = "create:crushed_raw_uranium"
unlock_message = "Nuclear Power researched."
dependency = "medcraft_steel_processing"

[items]
locked = [
  "protection_pixel:powerengine",
  "protection_pixel:heatoverlockingmechanism",
  "protection_pixel:heatpulsethruster",
  "protection_pixel:heatresistantceramicsheet",
  "create:crushed_raw_uranium"
]
always_unlocked = []

[blocks]
locked = []
always_unlocked = []

[recipes]
locked_ids = []
locked_items = [
  "protection_pixel:powerengine",
  "protection_pixel:heatoverlockingmechanism",
  "protection_pixel:heatpulsethruster",
  "protection_pixel:heatresistantceramicsheet",
  "create:crushed_raw_uranium"
]
always_unlocked = []
